# Generated by Django 5.2.14 on 2026-05-12 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_office_address', models.CharField(max_length=500)),
                ('home_terminal_address', models.CharField(max_length=500)),
                ('usdot_number', models.CharField(blank=True, max_length=20)),
                ('mc_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hos_schedule', models.CharField(default='70/8', max_length=10)),
            ],
            options={
                'db_table': 'carrier',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cdl_number', models.CharField(max_length=50)),
                ('license_state', models.CharField(max_length=2)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('using_34_restart', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.carrier')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('log_date', models.DateField()),
                ('total_miles_driven', models.IntegerField(default=0)),
                ('starting_odometer', models.IntegerField(blank=True, null=True)),
                ('ending_odometer', models.IntegerField(blank=True, null=True)),
                ('driving_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('on_duty_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('off_duty_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('sleeper_berth_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('thirty_min_break_taken', models.BooleanField(default=False)),
                ('thirty_min_break_time', models.TimeField(blank=True, null=True)),
                ('rolling_8day_total', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hours_remaining_70', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('using_split_sleeper', models.BooleanField(default=False)),
                ('split_sleeper_first_period', models.JSONField(blank=True, null=True)),
                ('split_sleeper_second_period', models.JSONField(blank=True, null=True)),
                ('log_grid_data', models.JSONField(blank=True, default=dict)),
                ('shipping_doc_number', models.CharField(blank=True, max_length=100)),
                ('shipper_name', models.CharField(blank=True, max_length=200)),
                ('commodity', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('driver_signature', models.CharField(blank=True, max_length=200)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='api.driver')),
            ],
            options={
                'db_table': 'daily_log',
                'ordering': ['trip', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='DutyStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('location', models.CharField(max_length=500)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_changes', to='api.dailylog')),
            ],
            options={
                'db_table': 'duty_status_change',
                'ordering': ['daily_log', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('gallons', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odometer_reading', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='api.dailylog')),
            ],
            options={
                'db_table': 'fuel_stop',
                'ordering': ['daily_log', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_number', models.CharField(blank=True, max_length=50)),
                ('license_plate', models.CharField(max_length=20)),
                ('license_state', models.CharField(max_length=2)),
                ('trailer_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='api.carrier')),
            ],
            options={
                'db_table': 'trailer',
                'ordering': ['trailer_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=500)),
                ('current_location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('current_location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('pickup_location', models.CharField(max_length=500)),
                ('pickup_location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('pickup_location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('dropoff_location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('dropoff_location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('total_distance_miles', models.IntegerField(blank=True, null=True)),
                ('total_driving_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('trip_start_date', models.DateField(blank=True, null=True)),
                ('trip_end_date', models.DateField(blank=True, null=True)),
                ('cycle_used_hours', models.DecimalField(decimal_places=1, default=0, help_text='Hours already on-duty in rolling 8-day window at trip start.', max_digits=5)),
                ('route_geometry_json', models.JSONField(blank=True, help_text='Decoded OSRM coordinates [[lng,lat], ...].', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.carrier')),
                ('driver', models.ForeignKey(blank=True, help_text='Django extension: who owns this planned trip (JWT).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.driver')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.trailer')),
            ],
            options={
                'db_table': 'trip',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='api.trip'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(blank=True, max_length=50)),
                ('license_plate', models.CharField(max_length=20)),
                ('license_state', models.CharField(max_length=2)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('has_sleeper_berth', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.carrier')),
            ],
            options={
                'db_table': 'vehicle',
                'ordering': ['truck_number'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.vehicle'),
        ),
    ]
