# Generated by Django 5.2.14 on 2026-05-11 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_office_street', models.CharField(max_length=255)),
                ('main_office_city', models.CharField(max_length=100)),
                ('main_office_state', models.CharField(max_length=2)),
                ('main_office_zip', models.CharField(max_length=20)),
                ('home_terminal_street', models.CharField(max_length=255)),
                ('home_terminal_city', models.CharField(max_length=100)),
                ('home_terminal_state', models.CharField(max_length=2)),
                ('home_terminal_zip', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('co_driver_name', models.CharField(blank=True, max_length=255)),
                ('license_state', models.CharField(max_length=2)),
                ('license_number', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.carrier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.TextField()),
                ('pickup_location', models.TextField()),
                ('dropoff_location', models.TextField()),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('miles_current_to_pickup', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('miles_pickup_to_dropoff', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_route_miles', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cycle_used_hours_8day', models.DecimalField(decimal_places=2, default=0, help_text='On-duty hours already used in rolling 8-day window (70h/8 property).', max_digits=5)),
                ('assumed_avg_mph', models.DecimalField(decimal_places=2, default=55, max_digits=5)),
                ('daily_start_local_time', models.CharField(default='06:00', max_length=5)),
                ('timezone', models.CharField(default='America/Chicago', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('demo_seeded', 'Demo seeded')], default='draft', max_length=32)),
                ('shipping_document_number', models.CharField(blank=True, max_length=128)),
                ('shipper_name', models.CharField(blank=True, max_length=255)),
                ('commodity', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('total_miles_driving', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('odometer_start', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odometer_end', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_on_duty_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('signature_line', models.CharField(default='Signed on file (demo)', max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='api.trip')),
            ],
            options={
                'ordering': ['log_date'],
                'unique_together': {('trip', 'log_date')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tractor_number', models.CharField(max_length=64)),
                ('tractor_plate', models.CharField(max_length=32)),
                ('tractor_plate_state', models.CharField(max_length=2)),
                ('trailer_number', models.CharField(max_length=64)),
                ('trailer_plate', models.CharField(max_length=32)),
                ('trailer_plate_state', models.CharField(max_length=2)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.carrier')),
            ],
            options={
                'ordering': ['tractor_number'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.vehicle'),
        ),
        migrations.CreateModel(
            name='CycleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField()),
                ('on_duty_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_days', to='api.driver')),
            ],
            options={
                'ordering': ['day_date'],
                'unique_together': {('driver', 'day_date')},
            },
        ),
        migrations.CreateModel(
            name='DutyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at_local', models.CharField(max_length=32)),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=32)),
                ('location_remark', models.TextField()),
                ('seq', models.PositiveIntegerField()),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_changes', to='api.dailylog')),
            ],
            options={
                'ordering': ['daily_log', 'seq'],
                'unique_together': {('daily_log', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('stop_type', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('fuel', 'Fuel'), ('break', 'Break'), ('dropoff', 'Dropoff'), ('rest', 'Rest'), ('other', 'Other')], max_length=32)),
                ('place_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('planned_arrive_local', models.CharField(blank=True, max_length=32)),
                ('planned_depart_local', models.CharField(blank=True, max_length=32)),
                ('dwell_minutes', models.PositiveIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.trip')),
            ],
            options={
                'ordering': ['trip', 'seq'],
                'unique_together': {('trip', 'seq')},
            },
        ),
    ]
