# Generated by Django 5.2.14 on 2026-05-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_schema_driver_eld'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['log_date', 'day_number']},
        ),
    ]
